// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bitly.OpenApiClient.Groups.Item.Agentic_traffic.Rollup;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Bitly.OpenApiClient.Groups.Item.Agentic_traffic
{
    /// <summary>
    /// Builds and executes requests for operations under \groups\{groupGuid}\agentic_traffic
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Agentic_trafficRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The rollup property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Groups.Item.Agentic_traffic.Rollup.RollupRequestBuilder Rollup
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Groups.Item.Agentic_traffic.Rollup.RollupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Groups.Item.Agentic_traffic.Agentic_trafficRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Agentic_trafficRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/groups/{groupGuid}/agentic_traffic", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Groups.Item.Agentic_traffic.Agentic_trafficRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Agentic_trafficRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/groups/{groupGuid}/agentic_traffic", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
