// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bitly.OpenApiClient.Groups.Item.Bitlinks.Item;
using Soenneker.Bitly.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Bitly.OpenApiClient.Groups.Item.Bitlinks
{
    /// <summary>
    /// Builds and executes requests for operations under \groups\{group_guid}\bitlinks
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BitlinksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Bitly.OpenApiClient.groups.item.bitlinks.item collection</summary>
        /// <param name="position">The type of sorting that you would like to do</param>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Groups.Item.Bitlinks.Item.WithSortItemRequestBuilder"/></returns>
        public global::Soenneker.Bitly.OpenApiClient.Groups.Item.Bitlinks.Item.WithSortItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("sort", position);
                return new global::Soenneker.Bitly.OpenApiClient.Groups.Item.Bitlinks.Item.WithSortItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Groups.Item.Bitlinks.BitlinksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BitlinksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/groups/{group_guid}/bitlinks{?archived*,campaign_guid*,channel_guid*,created_after*,created_before*,custom_bitlink*,deeplinks*,domain_deeplinks*,encoding_login*,has_qr_codes*,hostname_path_query*,launchpad_ids*,query*,search_after*,size*,tags*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Groups.Item.Bitlinks.BitlinksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BitlinksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/groups/{group_guid}/bitlinks{?archived*,campaign_guid*,channel_guid*,created_after*,created_before*,custom_bitlink*,deeplinks*,domain_deeplinks*,encoding_login*,has_qr_codes*,hostname_path_query*,launchpad_ids*,query*,search_after*,size*,tags*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a paginated collection of Bitlinks for a group. The list of custom bitlinks has newest entries first.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.Bitlinks"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.Forbidden">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.NotFound">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.InternalError">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.TemporarilyUnavailable">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Bitly.OpenApiClient.Models.Bitlinks?> GetAsync(Action<RequestConfiguration<global::Soenneker.Bitly.OpenApiClient.Groups.Item.Bitlinks.BitlinksRequestBuilder.BitlinksRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Bitly.OpenApiClient.Models.Bitlinks> GetAsync(Action<RequestConfiguration<global::Soenneker.Bitly.OpenApiClient.Groups.Item.Bitlinks.BitlinksRequestBuilder.BitlinksRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "403", global::Soenneker.Bitly.OpenApiClient.Models.Forbidden.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Bitly.OpenApiClient.Models.NotFound.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Bitly.OpenApiClient.Models.InternalError.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Bitly.OpenApiClient.Models.TemporarilyUnavailable.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Bitly.OpenApiClient.Models.Bitlinks>(requestInfo, global::Soenneker.Bitly.OpenApiClient.Models.Bitlinks.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Bulk update can add or remove tags or archive up to 100 links at a time; The response includes a list of bitlink ids that were updated.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.BulkUpdate"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.BadRequest">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.Forbidden">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.NotFound">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.UnprocessableEntity">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.InternalError">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.TemporarilyUnavailable">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Bitly.OpenApiClient.Models.BulkUpdate?> PatchAsync(global::Soenneker.Bitly.OpenApiClient.Models.BulkUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Bitly.OpenApiClient.Models.BulkUpdate> PatchAsync(global::Soenneker.Bitly.OpenApiClient.Models.BulkUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Bitly.OpenApiClient.Models.BadRequest.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Bitly.OpenApiClient.Models.Forbidden.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Bitly.OpenApiClient.Models.NotFound.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Bitly.OpenApiClient.Models.UnprocessableEntity.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Bitly.OpenApiClient.Models.InternalError.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Bitly.OpenApiClient.Models.TemporarilyUnavailable.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Bitly.OpenApiClient.Models.BulkUpdate>(requestInfo, global::Soenneker.Bitly.OpenApiClient.Models.BulkUpdate.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a paginated collection of Bitlinks for a group. The list of custom bitlinks has newest entries first.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Bitly.OpenApiClient.Groups.Item.Bitlinks.BitlinksRequestBuilder.BitlinksRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Bitly.OpenApiClient.Groups.Item.Bitlinks.BitlinksRequestBuilder.BitlinksRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Bulk update can add or remove tags or archive up to 100 links at a time; The response includes a list of bitlink ids that were updated.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Bitly.OpenApiClient.Models.BulkUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Bitly.OpenApiClient.Models.BulkUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Groups.Item.Bitlinks.BitlinksRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Bitly.OpenApiClient.Groups.Item.Bitlinks.BitlinksRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Bitly.OpenApiClient.Groups.Item.Bitlinks.BitlinksRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a paginated collection of Bitlinks for a group. The list of custom bitlinks has newest entries first.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BitlinksRequestBuilderGetQueryParameters 
        {
            /// <summary>Whether or not to include archived resources</summary>
            [Obsolete("This property is deprecated, use ArchivedAsGetArchivedQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("archived")]
            public string? Archived { get; set; }
#nullable restore
#else
            [QueryParameter("archived")]
            public string Archived { get; set; }
#endif
            /// <summary>Whether or not to include archived resources</summary>
            [QueryParameter("archived")]
            public global::Soenneker.Bitly.OpenApiClient.Groups.Item.Bitlinks.GetArchivedQueryParameterType? ArchivedAsGetArchivedQueryParameterType { get; set; }
            /// <summary>Filter to return only links for the given campaign GUID, can be provided</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("campaign_guid")]
            public string? CampaignGuid { get; set; }
#nullable restore
#else
            [QueryParameter("campaign_guid")]
            public string CampaignGuid { get; set; }
#endif
            /// <summary>Filter to return only links for the given channel GUID, can be provided, overrides all other parameters</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("channel_guid")]
            public string? ChannelGuid { get; set; }
#nullable restore
#else
            [QueryParameter("channel_guid")]
            public string ChannelGuid { get; set; }
#endif
            /// <summary>Timestamp as an integer unix epoch (seconds only)</summary>
            [QueryParameter("created_after")]
            public int? CreatedAfter { get; set; }
            /// <summary>Timestamp as an integer unix epoch (seconds only)</summary>
            [QueryParameter("created_before")]
            public int? CreatedBefore { get; set; }
            [Obsolete("This property is deprecated, use CustomBitlinkAsGetCustomBitlinkQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("custom_bitlink")]
            public string? CustomBitlink { get; set; }
#nullable restore
#else
            [QueryParameter("custom_bitlink")]
            public string CustomBitlink { get; set; }
#endif
            [QueryParameter("custom_bitlink")]
            public global::Soenneker.Bitly.OpenApiClient.Groups.Item.Bitlinks.GetCustom_bitlinkQueryParameterType? CustomBitlinkAsGetCustomBitlinkQueryParameterType { get; set; }
            /// <summary>Filter to only Bitlinks that contain deeplinks</summary>
            [Obsolete("This property is deprecated, use DeeplinksAsGetDeeplinksQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("deeplinks")]
            public string? Deeplinks { get; set; }
#nullable restore
#else
            [QueryParameter("deeplinks")]
            public string Deeplinks { get; set; }
#endif
            /// <summary>Filter to only Bitlinks that contain deeplinks</summary>
            [QueryParameter("deeplinks")]
            public global::Soenneker.Bitly.OpenApiClient.Groups.Item.Bitlinks.GetDeeplinksQueryParameterType? DeeplinksAsGetDeeplinksQueryParameterType { get; set; }
            /// <summary>Filter to only Bitlinks that contain deeplinks configured with a custom domain</summary>
            [Obsolete("This property is deprecated, use DomainDeeplinksAsGetDomainDeeplinksQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("domain_deeplinks")]
            public string? DomainDeeplinks { get; set; }
#nullable restore
#else
            [QueryParameter("domain_deeplinks")]
            public string DomainDeeplinks { get; set; }
#endif
            /// <summary>Filter to only Bitlinks that contain deeplinks configured with a custom domain</summary>
            [QueryParameter("domain_deeplinks")]
            public global::Soenneker.Bitly.OpenApiClient.Groups.Item.Bitlinks.GetDomain_deeplinksQueryParameterType? DomainDeeplinksAsGetDomainDeeplinksQueryParameterType { get; set; }
            /// <summary>Filter by the login of the authenticated user that created the Bitlink</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("encoding_login")]
            public string[]? EncodingLogin { get; set; }
#nullable restore
#else
            [QueryParameter("encoding_login")]
            public string[] EncodingLogin { get; set; }
#endif
            /// <summary>a filter value if the resource has any QR codes</summary>
            [Obsolete("This property is deprecated, use HasQrCodesAsGetHasQrCodesQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("has_qr_codes")]
            public string? HasQrCodes { get; set; }
#nullable restore
#else
            [QueryParameter("has_qr_codes")]
            public string HasQrCodes { get; set; }
#endif
            /// <summary>a filter value if the resource has any QR codes</summary>
            [QueryParameter("has_qr_codes")]
            public global::Soenneker.Bitly.OpenApiClient.Groups.Item.Bitlinks.GetHas_qr_codesQueryParameterType? HasQrCodesAsGetHasQrCodesQueryParameterType { get; set; }
            /// <summary>The hostname and/or path you would like to search (case-insensitive). Subdomains included; query params and fragment ignored.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("hostname_path_query")]
            public string? HostnamePathQuery { get; set; }
#nullable restore
#else
            [QueryParameter("hostname_path_query")]
            public string HostnamePathQuery { get; set; }
#endif
            /// <summary>Filter by launchpad id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("launchpad_ids")]
            public string[]? LaunchpadIds { get; set; }
#nullable restore
#else
            [QueryParameter("launchpad_ids")]
            public string[] LaunchpadIds { get; set; }
#endif
            /// <summary>The value that you would like to search</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("query")]
            public string? Query { get; set; }
#nullable restore
#else
            [QueryParameter("query")]
            public string Query { get; set; }
#endif
            /// <summary>Token used to search next batch, only use response from API as input value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("search_after")]
            public string? SearchAfter { get; set; }
#nullable restore
#else
            [QueryParameter("search_after")]
            public string SearchAfter { get; set; }
#endif
            /// <summary>The quantity of items to be be returned</summary>
            [QueryParameter("size")]
            public int? Size { get; set; }
            /// <summary>Filter by given tags</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tags")]
            public string[]? Tags { get; set; }
#nullable restore
#else
            [QueryParameter("tags")]
            public string[] Tags { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BitlinksRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Bitly.OpenApiClient.Groups.Item.Bitlinks.BitlinksRequestBuilder.BitlinksRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BitlinksRequestBuilderPatchRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
