// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bitly.OpenApiClient.Models;
using Soenneker.Bitly.OpenApiClient.Organizations.Item.Plan_limits;
using Soenneker.Bitly.OpenApiClient.Organizations.Item.Shorten_counts;
using Soenneker.Bitly.OpenApiClient.Organizations.Item.Shorten_counts_by_group;
using Soenneker.Bitly.OpenApiClient.Organizations.Item.Webhooks;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Bitly.OpenApiClient.Organizations.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \organizations\{organization_guid}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithOrganization_guItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The plan_limits property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Organizations.Item.Plan_limits.Plan_limitsRequestBuilder Plan_limits
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Organizations.Item.Plan_limits.Plan_limitsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shorten_counts property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Organizations.Item.Shorten_counts.Shorten_countsRequestBuilder Shorten_counts
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Organizations.Item.Shorten_counts.Shorten_countsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shorten_counts_by_group property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Organizations.Item.Shorten_counts_by_group.Shorten_counts_by_groupRequestBuilder Shorten_counts_by_group
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Organizations.Item.Shorten_counts_by_group.Shorten_counts_by_groupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooks property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Organizations.Item.Webhooks.WebhooksRequestBuilder Webhooks
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Organizations.Item.Webhooks.WebhooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Organizations.Item.WithOrganization_guItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithOrganization_guItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/organizations/{organization_guid}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Organizations.Item.WithOrganization_guItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithOrganization_guItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/organizations/{organization_guid}", rawUrl)
        {
        }
        /// <summary>
        /// Retrive details for the specified organization.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.Organization"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.Forbidden">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.NotFound">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.InternalError">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.TemporarilyUnavailable">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Bitly.OpenApiClient.Models.Organization?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Bitly.OpenApiClient.Models.Organization> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "403", global::Soenneker.Bitly.OpenApiClient.Models.Forbidden.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Bitly.OpenApiClient.Models.NotFound.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Bitly.OpenApiClient.Models.InternalError.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Bitly.OpenApiClient.Models.TemporarilyUnavailable.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Bitly.OpenApiClient.Models.Organization>(requestInfo, global::Soenneker.Bitly.OpenApiClient.Models.Organization.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrive details for the specified organization.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Organizations.Item.WithOrganization_guItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Bitly.OpenApiClient.Organizations.Item.WithOrganization_guItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Bitly.OpenApiClient.Organizations.Item.WithOrganization_guItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithOrganization_guItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
