// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bitly.OpenApiClient.Sites.Item.Redirects.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Bitly.OpenApiClient.Sites.Item.Redirects.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \sites\{launchpad-id}\redirects\{domain}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDomainItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Bitly.OpenApiClient.sites.item.redirects.item.item collection</summary>
        /// <param name="position">The keyword (back-half) of the redirect to delete</param>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Sites.Item.Redirects.Item.Item.WithKeywordItemRequestBuilder"/></returns>
        public global::Soenneker.Bitly.OpenApiClient.Sites.Item.Redirects.Item.Item.WithKeywordItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("keyword", position);
                return new global::Soenneker.Bitly.OpenApiClient.Sites.Item.Redirects.Item.Item.WithKeywordItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Sites.Item.Redirects.Item.WithDomainItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDomainItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sites/{launchpad%2Did}/redirects/{domain}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Sites.Item.Redirects.Item.WithDomainItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDomainItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sites/{launchpad%2Did}/redirects/{domain}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
