// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AggregateClicksForBitlinksByFacet : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The facet property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Facet { get; set; }
#nullable restore
#else
        public string Facet { get; set; }
#endif
        /// <summary>The info property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Info { get; set; }
#nullable restore
#else
        public string Info { get; set; }
#endif
        /// <summary>The totals_for_time_period property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bitly.OpenApiClient.Models.ClicksByFacet>? TotalsForTimePeriod { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bitly.OpenApiClient.Models.ClicksByFacet> TotalsForTimePeriod { get; set; }
#endif
        /// <summary>The unit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Unit { get; set; }
#nullable restore
#else
        public string Unit { get; set; }
#endif
        /// <summary>The unit_reference property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UnitReference { get; set; }
#nullable restore
#else
        public string UnitReference { get; set; }
#endif
        /// <summary>The units property</summary>
        public double? Units { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Models.AggregateClicksForBitlinksByFacet"/> and sets the default values.
        /// </summary>
        public AggregateClicksForBitlinksByFacet()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.AggregateClicksForBitlinksByFacet"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bitly.OpenApiClient.Models.AggregateClicksForBitlinksByFacet CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bitly.OpenApiClient.Models.AggregateClicksForBitlinksByFacet();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "facet", n => { Facet = n.GetStringValue(); } },
                { "info", n => { Info = n.GetStringValue(); } },
                { "totals_for_time_period", n => { TotalsForTimePeriod = n.GetCollectionOfObjectValues<global::Soenneker.Bitly.OpenApiClient.Models.ClicksByFacet>(global::Soenneker.Bitly.OpenApiClient.Models.ClicksByFacet.CreateFromDiscriminatorValue)?.AsList(); } },
                { "unit", n => { Unit = n.GetStringValue(); } },
                { "unit_reference", n => { UnitReference = n.GetStringValue(); } },
                { "units", n => { Units = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("facet", Facet);
            writer.WriteStringValue("info", Info);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bitly.OpenApiClient.Models.ClicksByFacet>("totals_for_time_period", TotalsForTimePeriod);
            writer.WriteStringValue("unit", Unit);
            writer.WriteStringValue("unit_reference", UnitReference);
            writer.WriteDoubleValue("units", Units);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
