// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BaseScanMetrics_facet
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "countries")]
        #pragma warning disable CS1591
        Countries,
        #pragma warning restore CS1591
        [EnumMember(Value = "cities")]
        #pragma warning disable CS1591
        Cities,
        #pragma warning restore CS1591
        [EnumMember(Value = "device_os")]
        #pragma warning disable CS1591
        Device_os,
        #pragma warning restore CS1591
        [EnumMember(Value = "browsers")]
        #pragma warning disable CS1591
        Browsers,
        #pragma warning restore CS1591
    }
}
