// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    /// <summary>
    /// A Bitly Site plus its content blocks. Returned by getSite; the blocks field is only present when the request sets include_blocks to true.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BitlySiteWithBlocks : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The appearance property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteAppearance? Appearance { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteAppearance Appearance { get; set; }
#endif
        /// <summary>The site&apos;s draft content blocks, ordered by container and then by sort order within that container. Blocks nested inside a grid or carousel carry that container&apos;s ID in container_id. The field is absent unless include_blocks is true, and is an empty array when the site has no blocks.Blocks taken down by a Bitly admin are not returned. Every other draft block is, including ones that do not appear on the published site: check is_active for blocks that are hidden or scheduled, and is_sample for template placeholders that are still missing their destination. A block with is_sample true never renders on the published site, regardless of is_active.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bitly.OpenApiClient.Models.SiteBlock>? Blocks { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bitly.OpenApiClient.Models.SiteBlock> Blocks { get; set; }
#endif
        /// <summary>The button_count property</summary>
        public int? ButtonCount { get; set; }
        /// <summary>The content property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteContent? Content { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteContent Content { get; set; }
#endif
        /// <summary>The created property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Created { get; set; }
#nullable restore
#else
        public string Created { get; set; }
#endif
        /// <summary>The group_guid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupGuid { get; set; }
#nullable restore
#else
        public string GroupGuid { get; set; }
#endif
        /// <summary>The is_edited property</summary>
        public bool? IsEdited { get; set; }
        /// <summary>The last_published property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastPublished { get; set; }
#nullable restore
#else
        public string LastPublished { get; set; }
#endif
        /// <summary>The modified property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Modified { get; set; }
#nullable restore
#else
        public string Modified { get; set; }
#endif
        /// <summary>The qr_code_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? QrCodeId { get; set; }
#nullable restore
#else
        public string QrCodeId { get; set; }
#endif
        /// <summary>The redirects property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bitly.OpenApiClient.Models.SiteRedirects>? Redirects { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bitly.OpenApiClient.Models.SiteRedirects> Redirects { get; set; }
#endif
        /// <summary>The site_guid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SiteGuid { get; set; }
#nullable restore
#else
        public string SiteGuid { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteWithBlocks"/> and sets the default values.
        /// </summary>
        public BitlySiteWithBlocks()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteWithBlocks"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteWithBlocks CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteWithBlocks();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "appearance", n => { Appearance = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteAppearance>(global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteAppearance.CreateFromDiscriminatorValue); } },
                { "blocks", n => { Blocks = n.GetCollectionOfObjectValues<global::Soenneker.Bitly.OpenApiClient.Models.SiteBlock>(global::Soenneker.Bitly.OpenApiClient.Models.SiteBlock.CreateFromDiscriminatorValue)?.AsList(); } },
                { "button_count", n => { ButtonCount = n.GetIntValue(); } },
                { "content", n => { Content = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteContent>(global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteContent.CreateFromDiscriminatorValue); } },
                { "created", n => { Created = n.GetStringValue(); } },
                { "group_guid", n => { GroupGuid = n.GetStringValue(); } },
                { "is_edited", n => { IsEdited = n.GetBoolValue(); } },
                { "last_published", n => { LastPublished = n.GetStringValue(); } },
                { "modified", n => { Modified = n.GetStringValue(); } },
                { "qr_code_id", n => { QrCodeId = n.GetStringValue(); } },
                { "redirects", n => { Redirects = n.GetCollectionOfObjectValues<global::Soenneker.Bitly.OpenApiClient.Models.SiteRedirects>(global::Soenneker.Bitly.OpenApiClient.Models.SiteRedirects.CreateFromDiscriminatorValue)?.AsList(); } },
                { "site_guid", n => { SiteGuid = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteAppearance>("appearance", Appearance);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bitly.OpenApiClient.Models.SiteBlock>("blocks", Blocks);
            writer.WriteIntValue("button_count", ButtonCount);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteContent>("content", Content);
            writer.WriteStringValue("created", Created);
            writer.WriteStringValue("group_guid", GroupGuid);
            writer.WriteBoolValue("is_edited", IsEdited);
            writer.WriteStringValue("last_published", LastPublished);
            writer.WriteStringValue("modified", Modified);
            writer.WriteStringValue("qr_code_id", QrCodeId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bitly.OpenApiClient.Models.SiteRedirects>("redirects", Redirects);
            writer.WriteStringValue("site_guid", SiteGuid);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
