// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BitlySiteAppearance : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The avatar_image_guid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AvatarImageGuid { get; set; }
#nullable restore
#else
        public string AvatarImageGuid { get; set; }
#endif
        /// <summary>The avatar_image_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AvatarImageUrl { get; set; }
#nullable restore
#else
        public string AvatarImageUrl { get; set; }
#endif
        /// <summary>The background_color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BackgroundColor { get; set; }
#nullable restore
#else
        public string BackgroundColor { get; set; }
#endif
        /// <summary>Available image alignment types for Site background images</summary>
        public global::Soenneker.Bitly.OpenApiClient.Models.SiteImageAlignment? BackgroundImageAlignment { get; set; }
        /// <summary>The background_image_guid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BackgroundImageGuid { get; set; }
#nullable restore
#else
        public string BackgroundImageGuid { get; set; }
#endif
        /// <summary>The background_image_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BackgroundImageUrl { get; set; }
#nullable restore
#else
        public string BackgroundImageUrl { get; set; }
#endif
        /// <summary>The background_preference property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BackgroundPreference { get; set; }
#nullable restore
#else
        public string BackgroundPreference { get; set; }
#endif
        /// <summary>The bottom_background_color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BottomBackgroundColor { get; set; }
#nullable restore
#else
        public string BottomBackgroundColor { get; set; }
#endif
        /// <summary>The default_button_background_color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultButtonBackgroundColor { get; set; }
#nullable restore
#else
        public string DefaultButtonBackgroundColor { get; set; }
#endif
        /// <summary>The default_button_shadow property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultButtonShadow { get; set; }
#nullable restore
#else
        public string DefaultButtonShadow { get; set; }
#endif
        /// <summary>The default_button_shape property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultButtonShape { get; set; }
#nullable restore
#else
        public string DefaultButtonShape { get; set; }
#endif
        /// <summary>The default_button_text_color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultButtonTextColor { get; set; }
#nullable restore
#else
        public string DefaultButtonTextColor { get; set; }
#endif
        /// <summary>The default_social_icon_color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultSocialIconColor { get; set; }
#nullable restore
#else
        public string DefaultSocialIconColor { get; set; }
#endif
        /// <summary>The default_social_icon_layout property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultSocialIconLayout { get; set; }
#nullable restore
#else
        public string DefaultSocialIconLayout { get; set; }
#endif
        /// <summary>The default_social_icon_position property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultSocialIconPosition { get; set; }
#nullable restore
#else
        public string DefaultSocialIconPosition { get; set; }
#endif
        /// <summary>The description_color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DescriptionColor { get; set; }
#nullable restore
#else
        public string DescriptionColor { get; set; }
#endif
        /// <summary>The font property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Font { get; set; }
#nullable restore
#else
        public string Font { get; set; }
#endif
        /// <summary>The header_appearance property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteHeaderAppearance? HeaderAppearance { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteHeaderAppearance HeaderAppearance { get; set; }
#endif
        /// <summary>The hide_bitly_logo property</summary>
        public bool? HideBitlyLogo { get; set; }
        /// <summary>The layout property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Layout { get; set; }
#nullable restore
#else
        public string Layout { get; set; }
#endif
        /// <summary>The layout_v2 property</summary>
        public int? LayoutV2 { get; set; }
        /// <summary>Enum of style preference values on a Bitly Site</summary>
        public global::Soenneker.Bitly.OpenApiClient.Models.SiteStylePreference? StylePreference { get; set; }
        /// <summary>The text_color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TextColor { get; set; }
#nullable restore
#else
        public string TextColor { get; set; }
#endif
        /// <summary>The theme_id property</summary>
        public int? ThemeId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteAppearance"/> and sets the default values.
        /// </summary>
        public BitlySiteAppearance()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteAppearance"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteAppearance CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteAppearance();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "avatar_image_guid", n => { AvatarImageGuid = n.GetStringValue(); } },
                { "avatar_image_url", n => { AvatarImageUrl = n.GetStringValue(); } },
                { "background_color", n => { BackgroundColor = n.GetStringValue(); } },
                { "background_image_alignment", n => { BackgroundImageAlignment = n.GetEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.SiteImageAlignment>(); } },
                { "background_image_guid", n => { BackgroundImageGuid = n.GetStringValue(); } },
                { "background_image_url", n => { BackgroundImageUrl = n.GetStringValue(); } },
                { "background_preference", n => { BackgroundPreference = n.GetStringValue(); } },
                { "bottom_background_color", n => { BottomBackgroundColor = n.GetStringValue(); } },
                { "default_button_background_color", n => { DefaultButtonBackgroundColor = n.GetStringValue(); } },
                { "default_button_shadow", n => { DefaultButtonShadow = n.GetStringValue(); } },
                { "default_button_shape", n => { DefaultButtonShape = n.GetStringValue(); } },
                { "default_button_text_color", n => { DefaultButtonTextColor = n.GetStringValue(); } },
                { "default_social_icon_color", n => { DefaultSocialIconColor = n.GetStringValue(); } },
                { "default_social_icon_layout", n => { DefaultSocialIconLayout = n.GetStringValue(); } },
                { "default_social_icon_position", n => { DefaultSocialIconPosition = n.GetStringValue(); } },
                { "description_color", n => { DescriptionColor = n.GetStringValue(); } },
                { "font", n => { Font = n.GetStringValue(); } },
                { "header_appearance", n => { HeaderAppearance = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteHeaderAppearance>(global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteHeaderAppearance.CreateFromDiscriminatorValue); } },
                { "hide_bitly_logo", n => { HideBitlyLogo = n.GetBoolValue(); } },
                { "layout", n => { Layout = n.GetStringValue(); } },
                { "layout_v2", n => { LayoutV2 = n.GetIntValue(); } },
                { "style_preference", n => { StylePreference = n.GetEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.SiteStylePreference>(); } },
                { "text_color", n => { TextColor = n.GetStringValue(); } },
                { "theme_id", n => { ThemeId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("avatar_image_guid", AvatarImageGuid);
            writer.WriteStringValue("avatar_image_url", AvatarImageUrl);
            writer.WriteStringValue("background_color", BackgroundColor);
            writer.WriteEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.SiteImageAlignment>("background_image_alignment", BackgroundImageAlignment);
            writer.WriteStringValue("background_image_guid", BackgroundImageGuid);
            writer.WriteStringValue("background_image_url", BackgroundImageUrl);
            writer.WriteStringValue("background_preference", BackgroundPreference);
            writer.WriteStringValue("bottom_background_color", BottomBackgroundColor);
            writer.WriteStringValue("default_button_background_color", DefaultButtonBackgroundColor);
            writer.WriteStringValue("default_button_shadow", DefaultButtonShadow);
            writer.WriteStringValue("default_button_shape", DefaultButtonShape);
            writer.WriteStringValue("default_button_text_color", DefaultButtonTextColor);
            writer.WriteStringValue("default_social_icon_color", DefaultSocialIconColor);
            writer.WriteStringValue("default_social_icon_layout", DefaultSocialIconLayout);
            writer.WriteStringValue("default_social_icon_position", DefaultSocialIconPosition);
            writer.WriteStringValue("description_color", DescriptionColor);
            writer.WriteStringValue("font", Font);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteHeaderAppearance>("header_appearance", HeaderAppearance);
            writer.WriteBoolValue("hide_bitly_logo", HideBitlyLogo);
            writer.WriteStringValue("layout", Layout);
            writer.WriteIntValue("layout_v2", LayoutV2);
            writer.WriteEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.SiteStylePreference>("style_preference", StylePreference);
            writer.WriteStringValue("text_color", TextColor);
            writer.WriteIntValue("theme_id", ThemeId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
