// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustomBitlinkHistory : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bsd property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Bsd { get; set; }
#nullable restore
#else
        public string Bsd { get; set; }
#endif
        /// <summary>The created property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Created { get; set; }
#nullable restore
#else
        public string Created { get; set; }
#endif
        /// <summary>The deactivated property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Deactivated { get; set; }
#nullable restore
#else
        public string Deactivated { get; set; }
#endif
        /// <summary>The first_created property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstCreated { get; set; }
#nullable restore
#else
        public string FirstCreated { get; set; }
#endif
        /// <summary>The group_guid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupGuid { get; set; }
#nullable restore
#else
        public string GroupGuid { get; set; }
#endif
        /// <summary>The hash property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Hash { get; set; }
#nullable restore
#else
        public string Hash { get; set; }
#endif
        /// <summary>The is_active property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The keyword property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Keyword { get; set; }
#nullable restore
#else
        public string Keyword { get; set; }
#endif
        /// <summary>The login property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Login { get; set; }
#nullable restore
#else
        public string Login { get; set; }
#endif
        /// <summary>The long_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LongUrl { get; set; }
#nullable restore
#else
        public string LongUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Models.CustomBitlinkHistory"/> and sets the default values.
        /// </summary>
        public CustomBitlinkHistory()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.CustomBitlinkHistory"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bitly.OpenApiClient.Models.CustomBitlinkHistory CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bitly.OpenApiClient.Models.CustomBitlinkHistory();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bsd", n => { Bsd = n.GetStringValue(); } },
                { "created", n => { Created = n.GetStringValue(); } },
                { "deactivated", n => { Deactivated = n.GetStringValue(); } },
                { "first_created", n => { FirstCreated = n.GetStringValue(); } },
                { "group_guid", n => { GroupGuid = n.GetStringValue(); } },
                { "hash", n => { Hash = n.GetStringValue(); } },
                { "is_active", n => { IsActive = n.GetBoolValue(); } },
                { "keyword", n => { Keyword = n.GetStringValue(); } },
                { "login", n => { Login = n.GetStringValue(); } },
                { "long_url", n => { LongUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("bsd", Bsd);
            writer.WriteStringValue("created", Created);
            writer.WriteStringValue("deactivated", Deactivated);
            writer.WriteStringValue("first_created", FirstCreated);
            writer.WriteStringValue("group_guid", GroupGuid);
            writer.WriteStringValue("hash", Hash);
            writer.WriteBoolValue("is_active", IsActive);
            writer.WriteStringValue("keyword", Keyword);
            writer.WriteStringValue("login", Login);
            writer.WriteStringValue("long_url", LongUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
