// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustomBitlink : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bitlink property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.BitlinkBody? Bitlink { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.BitlinkBody Bitlink { get; set; }
#endif
        /// <summary>The bitlink_history property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bitly.OpenApiClient.Models.CustomBitlinkHistory>? BitlinkHistory { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bitly.OpenApiClient.Models.CustomBitlinkHistory> BitlinkHistory { get; set; }
#endif
        /// <summary>The custom_bitlink property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomBitlinkProp { get; set; }
#nullable restore
#else
        public string CustomBitlinkProp { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Models.CustomBitlink"/> and sets the default values.
        /// </summary>
        public CustomBitlink()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.CustomBitlink"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bitly.OpenApiClient.Models.CustomBitlink CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bitly.OpenApiClient.Models.CustomBitlink();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bitlink", n => { Bitlink = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.BitlinkBody>(global::Soenneker.Bitly.OpenApiClient.Models.BitlinkBody.CreateFromDiscriminatorValue); } },
                { "bitlink_history", n => { BitlinkHistory = n.GetCollectionOfObjectValues<global::Soenneker.Bitly.OpenApiClient.Models.CustomBitlinkHistory>(global::Soenneker.Bitly.OpenApiClient.Models.CustomBitlinkHistory.CreateFromDiscriminatorValue)?.AsList(); } },
                { "custom_bitlink", n => { CustomBitlinkProp = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.BitlinkBody>("bitlink", Bitlink);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bitly.OpenApiClient.Models.CustomBitlinkHistory>("bitlink_history", BitlinkHistory);
            writer.WriteStringValue("custom_bitlink", CustomBitlinkProp);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
