// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DigitalBusinessCardLayout
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "button")]
        #pragma warning disable CS1591
        Button,
        #pragma warning restore CS1591
        [EnumMember(Value = "card")]
        #pragma warning disable CS1591
        Card,
        #pragma warning restore CS1591
        [EnumMember(Value = "inline")]
        #pragma warning disable CS1591
        Inline,
        #pragma warning restore CS1591
    }
}
