// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DigitalBusinessCardContact : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bitlink_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BitlinkId { get; set; }
#nullable restore
#else
        public string BitlinkId { get; set; }
#endif
        /// <summary>The contact_method property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Models.DigitalBusinessCardContactContactMethod? ContactMethod { get; set; }
        /// <summary>The method_type property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Models.DigitalBusinessCardContactMethodType? MethodType { get; set; }
        /// <summary>The sort_order property</summary>
        public int? SortOrder { get; set; }
        /// <summary>The value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value { get; set; }
#nullable restore
#else
        public string Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Models.DigitalBusinessCardContact"/> and sets the default values.
        /// </summary>
        public DigitalBusinessCardContact()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.DigitalBusinessCardContact"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bitly.OpenApiClient.Models.DigitalBusinessCardContact CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bitly.OpenApiClient.Models.DigitalBusinessCardContact();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bitlink_id", n => { BitlinkId = n.GetStringValue(); } },
                { "contact_method", n => { ContactMethod = n.GetEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.DigitalBusinessCardContactContactMethod>(); } },
                { "method_type", n => { MethodType = n.GetEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.DigitalBusinessCardContactMethodType>(); } },
                { "sort_order", n => { SortOrder = n.GetIntValue(); } },
                { "value", n => { Value = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("bitlink_id", BitlinkId);
            writer.WriteEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.DigitalBusinessCardContactContactMethod>("contact_method", ContactMethod);
            writer.WriteEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.DigitalBusinessCardContactMethodType>("method_type", MethodType);
            writer.WriteIntValue("sort_order", SortOrder);
            writer.WriteStringValue("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
