// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    /// <summary>
    /// custom domain in validation queue
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DomainValidateBody : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The custom_domain property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomDomain { get; set; }
#nullable restore
#else
        public string CustomDomain { get; set; }
#endif
        /// <summary>The group_guids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? GroupGuids { get; set; }
#nullable restore
#else
        public List<string> GroupGuids { get; set; }
#endif
        /// <summary>The organization_guid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationGuid { get; set; }
#nullable restore
#else
        public string OrganizationGuid { get; set; }
#endif
        /// <summary>Check the domain without adding it. The response says whether the domain can be used, and no custom domain is created. Use this to catch a typo or a domain another account holds before you commit.</summary>
        public bool? Prevalidate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Models.DomainValidateBody"/> and sets the default values.
        /// </summary>
        public DomainValidateBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.DomainValidateBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bitly.OpenApiClient.Models.DomainValidateBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bitly.OpenApiClient.Models.DomainValidateBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "custom_domain", n => { CustomDomain = n.GetStringValue(); } },
                { "group_guids", n => { GroupGuids = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "organization_guid", n => { OrganizationGuid = n.GetStringValue(); } },
                { "prevalidate", n => { Prevalidate = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("custom_domain", CustomDomain);
            writer.WriteCollectionOfPrimitiveValues<string>("group_guids", GroupGuids);
            writer.WriteStringValue("organization_guid", OrganizationGuid);
            writer.WriteBoolValue("prevalidate", Prevalidate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
