// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DomainDns : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>the detected DNS provider for the requested domain</summary>
        public global::Soenneker.Bitly.OpenApiClient.Models.DomainDnsDnsProvider? DnsProvider { get; set; }
        /// <summary>the requested domain</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Domain { get; set; }
#nullable restore
#else
        public string Domain { get; set; }
#endif
        /// <summary>the records returned by the lookup</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Records { get; set; }
#nullable restore
#else
        public List<string> Records { get; set; }
#endif
        /// <summary>whether the returned records represent a valid configuration</summary>
        public bool? RecordsValid { get; set; }
        /// <summary>The records to create at your registrar for the domain to verify. A root domain needs the A records. A subdomain needs the CNAME record.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bitly.OpenApiClient.Models.DomainDnsRequiredRecordsItem>? RequiredRecords { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bitly.OpenApiClient.Models.DomainDnsRequiredRecordsItem> RequiredRecords { get; set; }
#endif
        /// <summary>the type of DNS record returned</summary>
        public global::Soenneker.Bitly.OpenApiClient.Models.DomainDnsType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Models.DomainDns"/> and sets the default values.
        /// </summary>
        public DomainDns()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.DomainDns"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bitly.OpenApiClient.Models.DomainDns CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bitly.OpenApiClient.Models.DomainDns();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dns_provider", n => { DnsProvider = n.GetEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.DomainDnsDnsProvider>(); } },
                { "domain", n => { Domain = n.GetStringValue(); } },
                { "records", n => { Records = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "records_valid", n => { RecordsValid = n.GetBoolValue(); } },
                { "required_records", n => { RequiredRecords = n.GetCollectionOfObjectValues<global::Soenneker.Bitly.OpenApiClient.Models.DomainDnsRequiredRecordsItem>(global::Soenneker.Bitly.OpenApiClient.Models.DomainDnsRequiredRecordsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.DomainDnsType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.DomainDnsDnsProvider>("dns_provider", DnsProvider);
            writer.WriteStringValue("domain", Domain);
            writer.WriteCollectionOfPrimitiveValues<string>("records", Records);
            writer.WriteBoolValue("records_valid", RecordsValid);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bitly.OpenApiClient.Models.DomainDnsRequiredRecordsItem>("required_records", RequiredRecords);
            writer.WriteEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.DomainDnsType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
