// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    /// <summary>Device type values for use in dynamic routing rules (device_match / device_exclude)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DynamicRoutingDeviceEnum
    {
        [EnumMember(Value = "mobile")]
        #pragma warning disable CS1591
        Mobile,
        #pragma warning restore CS1591
        [EnumMember(Value = "tablet")]
        #pragma warning disable CS1591
        Tablet,
        #pragma warning restore CS1591
        [EnumMember(Value = "desktop")]
        #pragma warning disable CS1591
        Desktop,
        #pragma warning restore CS1591
    }
}
