// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetGroupLinkClicksByDevice200ResponseFacet
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "countries")]
        #pragma warning disable CS1591
        Countries,
        #pragma warning restore CS1591
        [EnumMember(Value = "cities")]
        #pragma warning disable CS1591
        Cities,
        #pragma warning restore CS1591
        [EnumMember(Value = "devices")]
        #pragma warning disable CS1591
        Devices,
        #pragma warning restore CS1591
        [EnumMember(Value = "referrers")]
        #pragma warning disable CS1591
        Referrers,
        #pragma warning restore CS1591
        [EnumMember(Value = "referrers_by_domain")]
        #pragma warning disable CS1591
        ReferrersByDomain,
        #pragma warning restore CS1591
        [EnumMember(Value = "referring_domains")]
        #pragma warning disable CS1591
        ReferringDomains,
        #pragma warning restore CS1591
        [EnumMember(Value = "referring_networks")]
        #pragma warning disable CS1591
        ReferringNetworks,
        #pragma warning restore CS1591
        [EnumMember(Value = "shorten_counts")]
        #pragma warning disable CS1591
        ShortenCounts,
        #pragma warning restore CS1591
    }
}
