// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GroupHistoricalUsage : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>End date (format &quot;2006-01-02&quot;) of the historical usage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndDate { get; set; }
#nullable restore
#else
        public string EndDate { get; set; }
#endif
        /// <summary>the group&apos;s guid</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupGuid { get; set; }
#nullable restore
#else
        public string GroupGuid { get; set; }
#endif
        /// <summary>an array of all of the group&apos;s historical feature usage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bitly.OpenApiClient.Models.HistoricalFeatureUsage>? HistoricalLimitUsage { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bitly.OpenApiClient.Models.HistoricalFeatureUsage> HistoricalLimitUsage { get; set; }
#endif
        /// <summary>Start date (format &quot;2006-01-02&quot;) of the historical usage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartDate { get; set; }
#nullable restore
#else
        public string StartDate { get; set; }
#endif
        /// <summary>A unit of time (day, week, or month)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Unit { get; set; }
#nullable restore
#else
        public string Unit { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Models.GroupHistoricalUsage"/> and sets the default values.
        /// </summary>
        public GroupHistoricalUsage()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.GroupHistoricalUsage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bitly.OpenApiClient.Models.GroupHistoricalUsage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bitly.OpenApiClient.Models.GroupHistoricalUsage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "end_date", n => { EndDate = n.GetStringValue(); } },
                { "group_guid", n => { GroupGuid = n.GetStringValue(); } },
                { "historical_limit_usage", n => { HistoricalLimitUsage = n.GetCollectionOfObjectValues<global::Soenneker.Bitly.OpenApiClient.Models.HistoricalFeatureUsage>(global::Soenneker.Bitly.OpenApiClient.Models.HistoricalFeatureUsage.CreateFromDiscriminatorValue)?.AsList(); } },
                { "start_date", n => { StartDate = n.GetStringValue(); } },
                { "unit", n => { Unit = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("end_date", EndDate);
            writer.WriteStringValue("group_guid", GroupGuid);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bitly.OpenApiClient.Models.HistoricalFeatureUsage>("historical_limit_usage", HistoricalLimitUsage);
            writer.WriteStringValue("start_date", StartDate);
            writer.WriteStringValue("unit", Unit);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
