// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GroupExportResponse_export_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "link_engagements_batch")]
        #pragma warning disable CS1591
        Link_engagements_batch,
        #pragma warning restore CS1591
        [EnumMember(Value = "links_list")]
        #pragma warning disable CS1591
        Links_list,
        #pragma warning restore CS1591
        [EnumMember(Value = "qr_codes_list")]
        #pragma warning disable CS1591
        Qr_codes_list,
        #pragma warning restore CS1591
    }
}
