// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    /// <summary>Which export shape to produce.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GroupExportRequestBodyExportType
    {
        [EnumMember(Value = "link_engagements_batch")]
        #pragma warning disable CS1591
        LinkEngagementsBatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "links_list")]
        #pragma warning disable CS1591
        LinksList,
        #pragma warning restore CS1591
        [EnumMember(Value = "qr_codes_list")]
        #pragma warning disable CS1591
        QrCodesList,
        #pragma warning restore CS1591
    }
}
