// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum InstallPreference
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "no_install")]
        #pragma warning disable CS1591
        NoInstall,
        #pragma warning restore CS1591
        [EnumMember(Value = "auto_install")]
        #pragma warning disable CS1591
        AutoInstall,
        #pragma warning restore CS1591
        [EnumMember(Value = "promote_install")]
        #pragma warning disable CS1591
        PromoteInstall,
        #pragma warning restore CS1591
    }
}
