// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Organization : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bsds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Bsds { get; set; }
#nullable restore
#else
        public List<string> Bsds { get; set; }
#endif
        /// <summary>The created property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Created { get; set; }
#nullable restore
#else
        public string Created { get; set; }
#endif
        /// <summary>The guid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Guid { get; set; }
#nullable restore
#else
        public string Guid { get; set; }
#endif
        /// <summary>The is_active property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The modified property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Modified { get; set; }
#nullable restore
#else
        public string Modified { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The references property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.OrganizationReferences? References { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.OrganizationReferences References { get; set; }
#endif
        /// <summary>&quot;Two-factor authentication requirement for this organization. Possible values: \&quot;none\&quot;, \&quot;sms\&quot;. Omitted when no auth requirements are configured.&quot;</summary>
        public global::Soenneker.Bitly.OpenApiClient.Models.OrganizationRequire2Fa? Require2fa { get; set; }
        /// <summary>&quot;SSO authentication requirement for this organization. Possible values: \&quot;none\&quot;, \&quot;any\&quot;. Omitted when no auth requirements are configured.&quot;</summary>
        public global::Soenneker.Bitly.OpenApiClient.Models.OrganizationRequireSso? RequireSso { get; set; }
        /// <summary>The role property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Role { get; set; }
#nullable restore
#else
        public string Role { get; set; }
#endif
        /// <summary>The tier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tier { get; set; }
#nullable restore
#else
        public string Tier { get; set; }
#endif
        /// <summary>The tier_display_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TierDisplayName { get; set; }
#nullable restore
#else
        public string TierDisplayName { get; set; }
#endif
        /// <summary>The tier_family property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TierFamily { get; set; }
#nullable restore
#else
        public string TierFamily { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Models.Organization"/> and sets the default values.
        /// </summary>
        public Organization()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.Organization"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bitly.OpenApiClient.Models.Organization CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bitly.OpenApiClient.Models.Organization();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bsds", n => { Bsds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "created", n => { Created = n.GetStringValue(); } },
                { "guid", n => { Guid = n.GetStringValue(); } },
                { "is_active", n => { IsActive = n.GetBoolValue(); } },
                { "modified", n => { Modified = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "references", n => { References = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.OrganizationReferences>(global::Soenneker.Bitly.OpenApiClient.Models.OrganizationReferences.CreateFromDiscriminatorValue); } },
                { "require_2fa", n => { Require2fa = n.GetEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.OrganizationRequire2Fa>(); } },
                { "require_sso", n => { RequireSso = n.GetEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.OrganizationRequireSso>(); } },
                { "role", n => { Role = n.GetStringValue(); } },
                { "tier", n => { Tier = n.GetStringValue(); } },
                { "tier_display_name", n => { TierDisplayName = n.GetStringValue(); } },
                { "tier_family", n => { TierFamily = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("bsds", Bsds);
            writer.WriteStringValue("created", Created);
            writer.WriteStringValue("guid", Guid);
            writer.WriteBoolValue("is_active", IsActive);
            writer.WriteStringValue("modified", Modified);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.OrganizationReferences>("references", References);
            writer.WriteEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.OrganizationRequire2Fa>("require_2fa", Require2fa);
            writer.WriteEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.OrganizationRequireSso>("require_sso", RequireSso);
            writer.WriteStringValue("role", Role);
            writer.WriteStringValue("tier", Tier);
            writer.WriteStringValue("tier_display_name", TierDisplayName);
            writer.WriteStringValue("tier_family", TierFamily);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
