// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PlanLimits : global::Soenneker.Bitly.OpenApiClient.Models.HasReferences, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The organization_guid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationGuid { get; set; }
#nullable restore
#else
        public string OrganizationGuid { get; set; }
#endif
        /// <summary>The plan_limits property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bitly.OpenApiClient.Models.PlanLimit>? PlanLimitsProp { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bitly.OpenApiClient.Models.PlanLimit> PlanLimitsProp { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.PlanLimits"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Bitly.OpenApiClient.Models.PlanLimits CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bitly.OpenApiClient.Models.PlanLimits();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "organization_guid", n => { OrganizationGuid = n.GetStringValue(); } },
                { "plan_limits", n => { PlanLimitsProp = n.GetCollectionOfObjectValues<global::Soenneker.Bitly.OpenApiClient.Models.PlanLimit>(global::Soenneker.Bitly.OpenApiClient.Models.PlanLimit.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteStringValue("organization_guid", OrganizationGuid);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bitly.OpenApiClient.Models.PlanLimit>("plan_limits", PlanLimitsProp);
        }
    }
}
#pragma warning restore CS0618
