// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    /// <summary>
    /// Request body for generating a static QR code image. Customizations such as gradient, background_gradient, frame, text and logo are not supported.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PublicCreateStaticQRCodeRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The raw content to encode in the QR code (e.g. a URL).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Content { get; set; }
#nullable restore
#else
        public string Content { get; set; }
#endif
        /// <summary>The group (brand) GUID used for access control and analytics.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupGuid { get; set; }
#nullable restore
#else
        public string GroupGuid { get; set; }
#endif
        /// <summary>Appearance options for a static QR code. gradient, background_gradient, frame, text, and logo are not supported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCustomizationsStaticPublic? RenderCustomizations { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCustomizationsStaticPublic RenderCustomizations { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Models.PublicCreateStaticQRCodeRequest"/> and sets the default values.
        /// </summary>
        public PublicCreateStaticQRCodeRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.PublicCreateStaticQRCodeRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bitly.OpenApiClient.Models.PublicCreateStaticQRCodeRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bitly.OpenApiClient.Models.PublicCreateStaticQRCodeRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "content", n => { Content = n.GetStringValue(); } },
                { "group_guid", n => { GroupGuid = n.GetStringValue(); } },
                { "render_customizations", n => { RenderCustomizations = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCustomizationsStaticPublic>(global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCustomizationsStaticPublic.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("content", Content);
            writer.WriteStringValue("group_guid", GroupGuid);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCustomizationsStaticPublic>("render_customizations", RenderCustomizations);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
