// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum QrCodeFrameType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "border_only")]
        #pragma warning disable CS1591
        BorderOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "text_bottom")]
        #pragma warning disable CS1591
        TextBottom,
        #pragma warning restore CS1591
        [EnumMember(Value = "tooltip_bottom")]
        #pragma warning disable CS1591
        TooltipBottom,
        #pragma warning restore CS1591
        [EnumMember(Value = "arrow")]
        #pragma warning disable CS1591
        Arrow,
        #pragma warning restore CS1591
        [EnumMember(Value = "text_top")]
        #pragma warning disable CS1591
        TextTop,
        #pragma warning restore CS1591
        [EnumMember(Value = "text_bottom_in_frame")]
        #pragma warning disable CS1591
        TextBottomInFrame,
        #pragma warning restore CS1591
        [EnumMember(Value = "script")]
        #pragma warning disable CS1591
        Script,
        #pragma warning restore CS1591
        [EnumMember(Value = "text_top_and_bottom")]
        #pragma warning disable CS1591
        TextTopAndBottom,
        #pragma warning restore CS1591
        [EnumMember(Value = "url")]
        #pragma warning disable CS1591
        Url,
        #pragma warning restore CS1591
        [EnumMember(Value = "instagram")]
        #pragma warning disable CS1591
        Instagram,
        #pragma warning restore CS1591
    }
}
