// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    /// <summary>The type of dynamic/static content the QR serves, e.g. Link In Bio page, micro site, bitlink, email, text, Wifi, etc.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum QrCodeTypeEnum
    {
        [EnumMember(Value = "bitlink")]
        #pragma warning disable CS1591
        Bitlink,
        #pragma warning restore CS1591
        [EnumMember(Value = "long_url")]
        #pragma warning disable CS1591
        LongUrl,
        #pragma warning restore CS1591
        [EnumMember(Value = "link_in_bio")]
        #pragma warning disable CS1591
        LinkInBio,
        #pragma warning restore CS1591
        [EnumMember(Value = "v_card")]
        #pragma warning disable CS1591
        VCard,
        #pragma warning restore CS1591
        [EnumMember(Value = "wifi")]
        #pragma warning disable CS1591
        Wifi,
        #pragma warning restore CS1591
        [EnumMember(Value = "email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "phone")]
        #pragma warning disable CS1591
        Phone,
        #pragma warning restore CS1591
        [EnumMember(Value = "text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
    }
}
