// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class QrCodeGradient : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The angle by which the gradient will be rotated. Only applies to linear gradients.</summary>
        public double? Angle { get; set; }
        /// <summary>The list of hex colors and their offsets to be used in the gradient.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bitly.OpenApiClient.Models.GradientColor>? Colors { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bitly.OpenApiClient.Models.GradientColor> Colors { get; set; }
#endif
        /// <summary>Ignore gradient mask on corners</summary>
        public bool? ExcludeCorners { get; set; }
        /// <summary>The style of the gradient. Can be either linear or radial.</summary>
        public global::Soenneker.Bitly.OpenApiClient.Models.QrCodeGradientStyle? Style { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Models.QrCodeGradient"/> and sets the default values.
        /// </summary>
        public QrCodeGradient()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.QrCodeGradient"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bitly.OpenApiClient.Models.QrCodeGradient CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bitly.OpenApiClient.Models.QrCodeGradient();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "angle", n => { Angle = n.GetDoubleValue(); } },
                { "colors", n => { Colors = n.GetCollectionOfObjectValues<global::Soenneker.Bitly.OpenApiClient.Models.GradientColor>(global::Soenneker.Bitly.OpenApiClient.Models.GradientColor.CreateFromDiscriminatorValue)?.AsList(); } },
                { "exclude_corners", n => { ExcludeCorners = n.GetBoolValue(); } },
                { "style", n => { Style = n.GetEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.QrCodeGradientStyle>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("angle", Angle);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bitly.OpenApiClient.Models.GradientColor>("colors", Colors);
            writer.WriteBoolValue("exclude_corners", ExcludeCorners);
            writer.WriteEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.QrCodeGradientStyle>("style", Style);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
