// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class QRCodeDetails : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The archived property</summary>
        public bool? Archived { get; set; }
        /// <summary>The bitlink associated with the qr code. Not all qr codes are associated with one.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BitlinkId { get; set; }
#nullable restore
#else
        public string BitlinkId { get; set; }
#endif
        /// <summary>The created property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Created { get; set; }
#nullable restore
#else
        public string Created { get; set; }
#endif
        /// <summary>Optional expiration timestamp for the QR code&apos;s bitlink (e.g., 2025-01-28T14:30:00+0000)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExpirationAt { get; set; }
#nullable restore
#else
        public string ExpirationAt { get; set; }
#endif
        /// <summary>The group_guid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupGuid { get; set; }
#nullable restore
#else
        public string GroupGuid { get; set; }
#endif
        /// <summary>Contains GS1 related metadata</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.GS1Metadata? Gs1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.GS1Metadata Gs1 { get; set; }
#endif
        /// <summary>A list of destination URLs that the qr code leads to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? LongUrls { get; set; }
#nullable restore
#else
        public List<string> LongUrls { get; set; }
#endif
        /// <summary>The modified property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Modified { get; set; }
#nullable restore
#else
        public string Modified { get; set; }
#endif
        /// <summary>The qrcode_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? QrcodeId { get; set; }
#nullable restore
#else
        public string QrcodeId { get; set; }
#endif
        /// <summary>The type of dynamic/static content the QR serves, e.g. Link In Bio page, micro site, bitlink, email, text, Wifi, etc.</summary>
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeTypeEnum? QrCodeType { get; set; }
        /// <summary>Options for customizing a QR Code&apos;s appearance</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCustomizationsPublic? RenderCustomizations { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCustomizationsPublic RenderCustomizations { get; set; }
#endif
        /// <summary>The serialized string of the QR code&apos;s content</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SerializedContent { get; set; }
#nullable restore
#else
        public string SerializedContent { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Models.QRCodeDetails"/> and sets the default values.
        /// </summary>
        public QRCodeDetails()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.QRCodeDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bitly.OpenApiClient.Models.QRCodeDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bitly.OpenApiClient.Models.QRCodeDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "archived", n => { Archived = n.GetBoolValue(); } },
                { "bitlink_id", n => { BitlinkId = n.GetStringValue(); } },
                { "created", n => { Created = n.GetStringValue(); } },
                { "expiration_at", n => { ExpirationAt = n.GetStringValue(); } },
                { "group_guid", n => { GroupGuid = n.GetStringValue(); } },
                { "gs1", n => { Gs1 = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.GS1Metadata>(global::Soenneker.Bitly.OpenApiClient.Models.GS1Metadata.CreateFromDiscriminatorValue); } },
                { "long_urls", n => { LongUrls = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "modified", n => { Modified = n.GetStringValue(); } },
                { "qr_code_type", n => { QrCodeType = n.GetEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeTypeEnum>(); } },
                { "qrcode_id", n => { QrcodeId = n.GetStringValue(); } },
                { "render_customizations", n => { RenderCustomizations = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCustomizationsPublic>(global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCustomizationsPublic.CreateFromDiscriminatorValue); } },
                { "serialized_content", n => { SerializedContent = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("archived", Archived);
            writer.WriteStringValue("bitlink_id", BitlinkId);
            writer.WriteStringValue("created", Created);
            writer.WriteStringValue("expiration_at", ExpirationAt);
            writer.WriteStringValue("group_guid", GroupGuid);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.GS1Metadata>("gs1", Gs1);
            writer.WriteCollectionOfPrimitiveValues<string>("long_urls", LongUrls);
            writer.WriteStringValue("modified", Modified);
            writer.WriteStringValue("qrcode_id", QrcodeId);
            writer.WriteEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeTypeEnum>("qr_code_type", QrCodeType);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCustomizationsPublic>("render_customizations", RenderCustomizations);
            writer.WriteStringValue("serialized_content", SerializedContent);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
