// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    /// <summary>
    /// An object representing all three corners of the QR code. The corners corresponding to each property are: corner_1 = top left, corner_2 = top right, and corner_3 = bottom right
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QRCodeCorners : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Represents one corner, both inner and outer, of a QR code, with color and shape values</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner? Corner1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner Corner1 { get; set; }
#endif
        /// <summary>Represents one corner, both inner and outer, of a QR code, with color and shape values</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner? Corner2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner Corner2 { get; set; }
#endif
        /// <summary>Represents one corner, both inner and outer, of a QR code, with color and shape values</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner? Corner3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner Corner3 { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorners"/> and sets the default values.
        /// </summary>
        public QRCodeCorners()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorners"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorners CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorners();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "corner_1", n => { Corner1 = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner>(global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner.CreateFromDiscriminatorValue); } },
                { "corner_2", n => { Corner2 = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner>(global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner.CreateFromDiscriminatorValue); } },
                { "corner_3", n => { Corner3 = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner>(global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner>("corner_1", Corner1);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner>("corner_2", Corner2);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner>("corner_3", Corner3);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
