// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    /// <summary>
    /// Contains the center, top, and bottom text to be used in the QR code
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QRCodeText : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An object describing text with color</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.Text? Bottom { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.Text Bottom { get; set; }
#endif
        /// <summary>An object describing text with color</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.Text? Center { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.Text Center { get; set; }
#endif
        /// <summary>An object describing text with color</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.Text? Top { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.Text Top { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Models.QRCodeText"/> and sets the default values.
        /// </summary>
        public QRCodeText()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.QRCodeText"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bitly.OpenApiClient.Models.QRCodeText CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bitly.OpenApiClient.Models.QRCodeText();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bottom", n => { Bottom = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.Text>(global::Soenneker.Bitly.OpenApiClient.Models.Text.CreateFromDiscriminatorValue); } },
                { "center", n => { Center = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.Text>(global::Soenneker.Bitly.OpenApiClient.Models.Text.CreateFromDiscriminatorValue); } },
                { "top", n => { Top = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.Text>(global::Soenneker.Bitly.OpenApiClient.Models.Text.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.Text>("bottom", Bottom);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.Text>("center", Center);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.Text>("top", Top);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
