// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    /// <summary>
    /// Options for customizing a QR Code&apos;s appearance
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QRCodeCustomizationsPublic : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The QR code&apos;s background color in hex code format with values for alpha channel</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BackgroundColor { get; set; }
#nullable restore
#else
        public string BackgroundColor { get; set; }
#endif
        /// <summary>The background_gradient property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeGradient? BackgroundGradient { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeGradient BackgroundGradient { get; set; }
#endif
        /// <summary>The branding property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeBranding? Branding { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeBranding Branding { get; set; }
#endif
        /// <summary>An object representing all three corners of the QR code. The corners corresponding to each property are: corner_1 = top left, corner_2 = top right, and corner_3 = bottom right</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorners? Corners { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorners Corners { get; set; }
#endif
        /// <summary>The QR code&apos;s dot pattern color in hex code format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DotPatternColor { get; set; }
#nullable restore
#else
        public string DotPatternColor { get; set; }
#endif
        /// <summary>The dot_pattern_type property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeDotPatternType? DotPatternType { get; set; }
        /// <summary>The frame property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeFrameRequest? Frame { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeFrameRequest Frame { get; set; }
#endif
        /// <summary>The gradient property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeGradient? Gradient { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeGradient Gradient { get; set; }
#endif
        /// <summary>The logo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeLogoPublic? Logo { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeLogoPublic Logo { get; set; }
#endif
        /// <summary>The QR code&apos;s editable spec settings, which for now is just the error correction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeSpecSettingsPublic? SpecSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeSpecSettingsPublic SpecSettings { get; set; }
#endif
        /// <summary>Contains the center, top, and bottom text to be used in the QR code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeText? Text { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeText Text { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCustomizationsPublic"/> and sets the default values.
        /// </summary>
        public QRCodeCustomizationsPublic()
        {
            AdditionalData = new Dictionary<string, object>();
            DotPatternType = global::Soenneker.Bitly.OpenApiClient.Models.QRCodeDotPatternType.Standard;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCustomizationsPublic"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCustomizationsPublic CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCustomizationsPublic();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "background_color", n => { BackgroundColor = n.GetStringValue(); } },
                { "background_gradient", n => { BackgroundGradient = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeGradient>(global::Soenneker.Bitly.OpenApiClient.Models.QRCodeGradient.CreateFromDiscriminatorValue); } },
                { "branding", n => { Branding = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeBranding>(global::Soenneker.Bitly.OpenApiClient.Models.QRCodeBranding.CreateFromDiscriminatorValue); } },
                { "corners", n => { Corners = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorners>(global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorners.CreateFromDiscriminatorValue); } },
                { "dot_pattern_color", n => { DotPatternColor = n.GetStringValue(); } },
                { "dot_pattern_type", n => { DotPatternType = n.GetEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeDotPatternType>(); } },
                { "frame", n => { Frame = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeFrameRequest>(global::Soenneker.Bitly.OpenApiClient.Models.QRCodeFrameRequest.CreateFromDiscriminatorValue); } },
                { "gradient", n => { Gradient = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeGradient>(global::Soenneker.Bitly.OpenApiClient.Models.QRCodeGradient.CreateFromDiscriminatorValue); } },
                { "logo", n => { Logo = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeLogoPublic>(global::Soenneker.Bitly.OpenApiClient.Models.QRCodeLogoPublic.CreateFromDiscriminatorValue); } },
                { "spec_settings", n => { SpecSettings = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeSpecSettingsPublic>(global::Soenneker.Bitly.OpenApiClient.Models.QRCodeSpecSettingsPublic.CreateFromDiscriminatorValue); } },
                { "text", n => { Text = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeText>(global::Soenneker.Bitly.OpenApiClient.Models.QRCodeText.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("background_color", BackgroundColor);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeGradient>("background_gradient", BackgroundGradient);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeBranding>("branding", Branding);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorners>("corners", Corners);
            writer.WriteStringValue("dot_pattern_color", DotPatternColor);
            writer.WriteEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeDotPatternType>("dot_pattern_type", DotPatternType);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeFrameRequest>("frame", Frame);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeGradient>("gradient", Gradient);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeLogoPublic>("logo", Logo);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeSpecSettingsPublic>("spec_settings", SpecSettings);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeText>("text", Text);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
