// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    /// <summary>
    /// Options for customizing a QR Code&apos;s appearance
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QrCodeCustomizationsPublic : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The QR code&apos;s background color in hex code format with values for alpha channel</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BackgroundColor { get; set; }
#nullable restore
#else
        public string BackgroundColor { get; set; }
#endif
        /// <summary>The background_gradient property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.QrCodeGradient? BackgroundGradient { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.QrCodeGradient BackgroundGradient { get; set; }
#endif
        /// <summary>The branding property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.QrCodeBranding? Branding { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.QrCodeBranding Branding { get; set; }
#endif
        /// <summary>&quot;An object representing all three corners of the QR code. The corners corresponding to each property are: corner_1 = top left, corner_2 = top right, and corner_3 = bottom right&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.QrCodeCorners? Corners { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.QrCodeCorners Corners { get; set; }
#endif
        /// <summary>The QR code&apos;s dot pattern color in hex code format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DotPatternColor { get; set; }
#nullable restore
#else
        public string DotPatternColor { get; set; }
#endif
        /// <summary>The dot_pattern_type property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Models.QrCodeDotPatternType? DotPatternType { get; set; }
        /// <summary>The frame property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.QrCodeFrameRequest? Frame { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.QrCodeFrameRequest Frame { get; set; }
#endif
        /// <summary>The gradient property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.QrCodeGradient? Gradient { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.QrCodeGradient Gradient { get; set; }
#endif
        /// <summary>The logo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.QrCodeLogoPublic? Logo { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.QrCodeLogoPublic Logo { get; set; }
#endif
        /// <summary>The QR code&apos;s editable spec settings, which for now is just the error correction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.QrCodeSpecSettingsPublic? SpecSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.QrCodeSpecSettingsPublic SpecSettings { get; set; }
#endif
        /// <summary>Contains the center, top, and bottom text to be used in the QR code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.QrCodeText? Text { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.QrCodeText Text { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Models.QrCodeCustomizationsPublic"/> and sets the default values.
        /// </summary>
        public QrCodeCustomizationsPublic()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.QrCodeCustomizationsPublic"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bitly.OpenApiClient.Models.QrCodeCustomizationsPublic CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bitly.OpenApiClient.Models.QrCodeCustomizationsPublic();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "background_color", n => { BackgroundColor = n.GetStringValue(); } },
                { "background_gradient", n => { BackgroundGradient = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QrCodeGradient>(global::Soenneker.Bitly.OpenApiClient.Models.QrCodeGradient.CreateFromDiscriminatorValue); } },
                { "branding", n => { Branding = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QrCodeBranding>(global::Soenneker.Bitly.OpenApiClient.Models.QrCodeBranding.CreateFromDiscriminatorValue); } },
                { "corners", n => { Corners = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QrCodeCorners>(global::Soenneker.Bitly.OpenApiClient.Models.QrCodeCorners.CreateFromDiscriminatorValue); } },
                { "dot_pattern_color", n => { DotPatternColor = n.GetStringValue(); } },
                { "dot_pattern_type", n => { DotPatternType = n.GetEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.QrCodeDotPatternType>(); } },
                { "frame", n => { Frame = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QrCodeFrameRequest>(global::Soenneker.Bitly.OpenApiClient.Models.QrCodeFrameRequest.CreateFromDiscriminatorValue); } },
                { "gradient", n => { Gradient = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QrCodeGradient>(global::Soenneker.Bitly.OpenApiClient.Models.QrCodeGradient.CreateFromDiscriminatorValue); } },
                { "logo", n => { Logo = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QrCodeLogoPublic>(global::Soenneker.Bitly.OpenApiClient.Models.QrCodeLogoPublic.CreateFromDiscriminatorValue); } },
                { "spec_settings", n => { SpecSettings = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QrCodeSpecSettingsPublic>(global::Soenneker.Bitly.OpenApiClient.Models.QrCodeSpecSettingsPublic.CreateFromDiscriminatorValue); } },
                { "text", n => { Text = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QrCodeText>(global::Soenneker.Bitly.OpenApiClient.Models.QrCodeText.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("background_color", BackgroundColor);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QrCodeGradient>("background_gradient", BackgroundGradient);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QrCodeBranding>("branding", Branding);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QrCodeCorners>("corners", Corners);
            writer.WriteStringValue("dot_pattern_color", DotPatternColor);
            writer.WriteEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.QrCodeDotPatternType>("dot_pattern_type", DotPatternType);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QrCodeFrameRequest>("frame", Frame);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QrCodeGradient>("gradient", Gradient);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QrCodeLogoPublic>("logo", Logo);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QrCodeSpecSettingsPublic>("spec_settings", SpecSettings);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.QrCodeText>("text", Text);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
