// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    /// <summary>
    /// Represents one corner, both inner and outer, of a QR code, with color and shape values
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QRCodeCorner : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The inner color of a corner of the QR code in hex code format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InnerColor { get; set; }
#nullable restore
#else
        public string InnerColor { get; set; }
#endif
        /// <summary>The outer color of a corner of the QR code in hex code format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OuterColor { get; set; }
#nullable restore
#else
        public string OuterColor { get; set; }
#endif
        /// <summary>The shape one of the QR code&apos;s corners should take</summary>
        public global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner_shape? Shape { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner"/> and sets the default values.
        /// </summary>
        public QRCodeCorner()
        {
            AdditionalData = new Dictionary<string, object>();
            Shape = global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner_shape.Standard;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "inner_color", n => { InnerColor = n.GetStringValue(); } },
                { "outer_color", n => { OuterColor = n.GetStringValue(); } },
                { "shape", n => { Shape = n.GetEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner_shape>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("inner_color", InnerColor);
            writer.WriteStringValue("outer_color", OuterColor);
            writer.WriteEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeCorner_shape>("shape", Shape);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
