// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    /// <summary>Enum of the available text locations on a Bitly Site</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SiteTextLocation
    {
        [EnumMember(Value = "top")]
        #pragma warning disable CS1591
        Top,
        #pragma warning restore CS1591
        [EnumMember(Value = "contain")]
        #pragma warning disable CS1591
        Contain,
        #pragma warning restore CS1591
        [EnumMember(Value = "bottom")]
        #pragma warning disable CS1591
        Bottom,
        #pragma warning restore CS1591
    }
}
