// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    /// <summary>Available container types</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SiteContainerTypeEnum
    {
        [EnumMember(Value = "carousel")]
        #pragma warning disable CS1591
        Carousel,
        #pragma warning restore CS1591
        [EnumMember(Value = "grid")]
        #pragma warning disable CS1591
        Grid,
        #pragma warning restore CS1591
    }
}
