// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SiteViewMetricsFacet
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "views")]
        #pragma warning disable CS1591
        Views,
        #pragma warning restore CS1591
        [EnumMember(Value = "countries")]
        #pragma warning disable CS1591
        Countries,
        #pragma warning restore CS1591
        [EnumMember(Value = "referrers")]
        #pragma warning disable CS1591
        Referrers,
        #pragma warning restore CS1591
        [EnumMember(Value = "devices")]
        #pragma warning disable CS1591
        Devices,
        #pragma warning restore CS1591
    }
}
