// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    /// <summary>Enum of banner type options on a Bitly Site</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SiteBannerType
    {
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "hero")]
        #pragma warning disable CS1591
        Hero,
        #pragma warning restore CS1591
        [EnumMember(Value = "rounded_up")]
        #pragma warning disable CS1591
        RoundedUp,
        #pragma warning restore CS1591
        [EnumMember(Value = "gradient")]
        #pragma warning disable CS1591
        Gradient,
        #pragma warning restore CS1591
        [EnumMember(Value = "square")]
        #pragma warning disable CS1591
        Square,
        #pragma warning restore CS1591
        [EnumMember(Value = "frame")]
        #pragma warning disable CS1591
        Frame,
        #pragma warning restore CS1591
    }
}
