// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    /// <summary>Enum of the profile image type options on a Bitly Site</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SiteProfileImageType
    {
        [EnumMember(Value = "single")]
        #pragma warning disable CS1591
        Single,
        #pragma warning restore CS1591
        [EnumMember(Value = "repeating")]
        #pragma warning disable CS1591
        Repeating,
        #pragma warning restore CS1591
    }
}
