// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    /// <summary>Enum of profile image shapes on a Bitly Site</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SiteProfileImageShape
    {
        [EnumMember(Value = "round")]
        #pragma warning disable CS1591
        Round,
        #pragma warning restore CS1591
        [EnumMember(Value = "rounded_square")]
        #pragma warning disable CS1591
        RoundedSquare,
        #pragma warning restore CS1591
        [EnumMember(Value = "square")]
        #pragma warning disable CS1591
        Square,
        #pragma warning restore CS1591
    }
}
