// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TemplateCategory
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Link-in-bio")]
        #pragma warning disable CS1591
        LinkInBio,
        #pragma warning restore CS1591
        [EnumMember(Value = "Products and services")]
        #pragma warning disable CS1591
        ProductsAndServices,
        #pragma warning restore CS1591
        [EnumMember(Value = "Promotions")]
        #pragma warning disable CS1591
        Promotions,
        #pragma warning restore CS1591
        [EnumMember(Value = "Digital business card")]
        #pragma warning disable CS1591
        DigitalBusinessCard,
        #pragma warning restore CS1591
        [EnumMember(Value = "Image gallery")]
        #pragma warning disable CS1591
        ImageGallery,
        #pragma warning restore CS1591
        [EnumMember(Value = "Recommended")]
        #pragma warning disable CS1591
        Recommended,
        #pragma warning restore CS1591
    }
}
