// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Template : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The appearance property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteAppearance? Appearance { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteAppearance Appearance { get; set; }
#endif
        /// <summary>The blocks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bitly.OpenApiClient.Models.SiteBlock>? Blocks { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bitly.OpenApiClient.Models.SiteBlock> Blocks { get; set; }
#endif
        /// <summary>The categories property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Categories { get; set; }
#nullable restore
#else
        public List<string> Categories { get; set; }
#endif
        /// <summary>The content property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteContent? Content { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteContent Content { get; set; }
#endif
        /// <summary>The created property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Created { get; set; }
#nullable restore
#else
        public string Created { get; set; }
#endif
        /// <summary>The is_active property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The is_paid property</summary>
        public bool? IsPaid { get; set; }
        /// <summary>The modified property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Modified { get; set; }
#nullable restore
#else
        public string Modified { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The template_guid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TemplateGuid { get; set; }
#nullable restore
#else
        public string TemplateGuid { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Models.Template"/> and sets the default values.
        /// </summary>
        public Template()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.Template"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bitly.OpenApiClient.Models.Template CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bitly.OpenApiClient.Models.Template();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "appearance", n => { Appearance = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteAppearance>(global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteAppearance.CreateFromDiscriminatorValue); } },
                { "blocks", n => { Blocks = n.GetCollectionOfObjectValues<global::Soenneker.Bitly.OpenApiClient.Models.SiteBlock>(global::Soenneker.Bitly.OpenApiClient.Models.SiteBlock.CreateFromDiscriminatorValue)?.AsList(); } },
                { "categories", n => { Categories = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "content", n => { Content = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteContent>(global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteContent.CreateFromDiscriminatorValue); } },
                { "created", n => { Created = n.GetStringValue(); } },
                { "is_active", n => { IsActive = n.GetBoolValue(); } },
                { "is_paid", n => { IsPaid = n.GetBoolValue(); } },
                { "modified", n => { Modified = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "template_guid", n => { TemplateGuid = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteAppearance>("appearance", Appearance);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bitly.OpenApiClient.Models.SiteBlock>("blocks", Blocks);
            writer.WriteCollectionOfPrimitiveValues<string>("categories", Categories);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.BitlySiteContent>("content", Content);
            writer.WriteStringValue("created", Created);
            writer.WriteBoolValue("is_active", IsActive);
            writer.WriteBoolValue("is_paid", IsPaid);
            writer.WriteStringValue("modified", Modified);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("template_guid", TemplateGuid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
