// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TextBlockAppearanceRequestFontSizeEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "small")]
        #pragma warning disable CS1591
        Small,
        #pragma warning restore CS1591
        [EnumMember(Value = "medium")]
        #pragma warning disable CS1591
        Medium,
        #pragma warning restore CS1591
        [EnumMember(Value = "large")]
        #pragma warning disable CS1591
        Large,
        #pragma warning restore CS1591
        [EnumMember(Value = "extra_large")]
        #pragma warning disable CS1591
        ExtraLarge,
        #pragma warning restore CS1591
    }
}
