// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TextBlockAppearanceRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The alignment property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Models.TextBlockAppearanceRequestAlignmentEnum? Alignment { get; set; }
        /// <summary>The background_color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BackgroundColor { get; set; }
#nullable restore
#else
        public string BackgroundColor { get; set; }
#endif
        /// <summary>The font_size property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Models.TextBlockAppearanceRequestFontSizeEnum? FontSize { get; set; }
        /// <summary>The text_block_style property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bitly.OpenApiClient.Models.TextBlockStyle? TextBlockStyle { get; set; }
#nullable restore
#else
        public global::Soenneker.Bitly.OpenApiClient.Models.TextBlockStyle TextBlockStyle { get; set; }
#endif
        /// <summary>The text_color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TextColor { get; set; }
#nullable restore
#else
        public string TextColor { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Models.TextBlockAppearanceRequest"/> and sets the default values.
        /// </summary>
        public TextBlockAppearanceRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.TextBlockAppearanceRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bitly.OpenApiClient.Models.TextBlockAppearanceRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bitly.OpenApiClient.Models.TextBlockAppearanceRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alignment", n => { Alignment = n.GetEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.TextBlockAppearanceRequestAlignmentEnum>(); } },
                { "background_color", n => { BackgroundColor = n.GetStringValue(); } },
                { "font_size", n => { FontSize = n.GetEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.TextBlockAppearanceRequestFontSizeEnum>(); } },
                { "text_block_style", n => { TextBlockStyle = n.GetObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.TextBlockStyle>(global::Soenneker.Bitly.OpenApiClient.Models.TextBlockStyle.CreateFromDiscriminatorValue); } },
                { "text_color", n => { TextColor = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.TextBlockAppearanceRequestAlignmentEnum>("alignment", Alignment);
            writer.WriteStringValue("background_color", BackgroundColor);
            writer.WriteEnumValue<global::Soenneker.Bitly.OpenApiClient.Models.TextBlockAppearanceRequestFontSizeEnum>("font_size", FontSize);
            writer.WriteObjectValue<global::Soenneker.Bitly.OpenApiClient.Models.TextBlockStyle>("text_block_style", TextBlockStyle);
            writer.WriteStringValue("text_color", TextColor);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
