// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    /// <summary>the unit of time queried for (day, week, month)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TimeUnitDWM
    {
        [EnumMember(Value = "day")]
        #pragma warning disable CS1591
        Day,
        #pragma warning restore CS1591
        [EnumMember(Value = "week")]
        #pragma warning disable CS1591
        Week,
        #pragma warning restore CS1591
        [EnumMember(Value = "month")]
        #pragma warning disable CS1591
        Month,
        #pragma warning restore CS1591
    }
}
