// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bitly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class User : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Created { get; set; }
#nullable restore
#else
        public string Created { get; set; }
#endif
        /// <summary>The default_group_guid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultGroupGuid { get; set; }
#nullable restore
#else
        public string DefaultGroupGuid { get; set; }
#endif
        /// <summary>The emails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bitly.OpenApiClient.Models.Email>? Emails { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bitly.OpenApiClient.Models.Email> Emails { get; set; }
#endif
        /// <summary>The is_2fa_enabled property</summary>
        public bool? Is2faEnabled { get; set; }
        /// <summary>The is_active property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The is_sso_user property</summary>
        public bool? IsSsoUser { get; set; }
        /// <summary>The login property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Login { get; set; }
#nullable restore
#else
        public string Login { get; set; }
#endif
        /// <summary>The modified property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Modified { get; set; }
#nullable restore
#else
        public string Modified { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Models.User"/> and sets the default values.
        /// </summary>
        public User()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.User"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bitly.OpenApiClient.Models.User CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bitly.OpenApiClient.Models.User();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created", n => { Created = n.GetStringValue(); } },
                { "default_group_guid", n => { DefaultGroupGuid = n.GetStringValue(); } },
                { "emails", n => { Emails = n.GetCollectionOfObjectValues<global::Soenneker.Bitly.OpenApiClient.Models.Email>(global::Soenneker.Bitly.OpenApiClient.Models.Email.CreateFromDiscriminatorValue)?.AsList(); } },
                { "is_2fa_enabled", n => { Is2faEnabled = n.GetBoolValue(); } },
                { "is_active", n => { IsActive = n.GetBoolValue(); } },
                { "is_sso_user", n => { IsSsoUser = n.GetBoolValue(); } },
                { "login", n => { Login = n.GetStringValue(); } },
                { "modified", n => { Modified = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("created", Created);
            writer.WriteStringValue("default_group_guid", DefaultGroupGuid);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bitly.OpenApiClient.Models.Email>("emails", Emails);
            writer.WriteBoolValue("is_2fa_enabled", Is2faEnabled);
            writer.WriteBoolValue("is_active", IsActive);
            writer.WriteBoolValue("is_sso_user", IsSsoUser);
            writer.WriteStringValue("login", Login);
            writer.WriteStringValue("modified", Modified);
            writer.WriteStringValue("name", Name);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
