// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bitly.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Bitly.OpenApiClient.Groups.Item.QrCodes
{
    /// <summary>
    /// Builds and executes requests for operations under \groups\{groupGuid}\qr-codes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QrCodesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Groups.Item.QrCodes.QrCodesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QrCodesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/groups/{groupGuid}/qr-codes{?archived*,created_after*,created_before*,creating_login*,has_expiration*,has_render_customizations*,hostname_path_query*,is_expired*,is_gs1*,qrc_type*,query*,search_after*,size*,tags*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Groups.Item.QrCodes.QrCodesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QrCodesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/groups/{groupGuid}/qr-codes{?archived*,created_after*,created_before*,creating_login*,has_expiration*,has_render_customizations*,hostname_path_query*,is_expired*,is_gs1*,qrc_type*,query*,search_after*,size*,tags*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves a list of QR codes matching the filter settings. Values are in reverse chronological order.The pagination occurs by calling the next link in the pagination response object.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.QrCodesMinimal"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.Forbidden">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.MonthlyLimitExceeded">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.InternalError">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Bitly.OpenApiClient.Models.QrCodesMinimal?> GetAsync(Action<RequestConfiguration<global::Soenneker.Bitly.OpenApiClient.Groups.Item.QrCodes.QrCodesRequestBuilder.QrCodesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Bitly.OpenApiClient.Models.QrCodesMinimal> GetAsync(Action<RequestConfiguration<global::Soenneker.Bitly.OpenApiClient.Groups.Item.QrCodes.QrCodesRequestBuilder.QrCodesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "403", global::Soenneker.Bitly.OpenApiClient.Models.Forbidden.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Bitly.OpenApiClient.Models.MonthlyLimitExceeded.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Bitly.OpenApiClient.Models.InternalError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Bitly.OpenApiClient.Models.QrCodesMinimal>(requestInfo, global::Soenneker.Bitly.OpenApiClient.Models.QrCodesMinimal.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Bulk update can add or remove tags, or archive/un-archive, up to 100 QR codes at a time.Pages QR codes cannot be updated with this endpoint.The response includes a list of QR code ids that were updated.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.QrcBulkUpdate"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.BadRequest">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.Forbidden">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.NotFound">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.Gone">When receiving a 410 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.UnprocessableEntity">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.MonthlyLimitExceeded">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.InternalError">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.TemporarilyUnavailable">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Bitly.OpenApiClient.Models.QrcBulkUpdate?> PatchAsync(global::Soenneker.Bitly.OpenApiClient.Models.QrcBulkUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Bitly.OpenApiClient.Models.QrcBulkUpdate> PatchAsync(global::Soenneker.Bitly.OpenApiClient.Models.QrcBulkUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Bitly.OpenApiClient.Models.BadRequest.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Bitly.OpenApiClient.Models.Forbidden.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Bitly.OpenApiClient.Models.NotFound.CreateFromDiscriminatorValue },
                { "410", global::Soenneker.Bitly.OpenApiClient.Models.Gone.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Bitly.OpenApiClient.Models.UnprocessableEntity.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Bitly.OpenApiClient.Models.MonthlyLimitExceeded.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Bitly.OpenApiClient.Models.InternalError.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Bitly.OpenApiClient.Models.TemporarilyUnavailable.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Bitly.OpenApiClient.Models.QrcBulkUpdate>(requestInfo, global::Soenneker.Bitly.OpenApiClient.Models.QrcBulkUpdate.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves a list of QR codes matching the filter settings. Values are in reverse chronological order.The pagination occurs by calling the next link in the pagination response object.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Bitly.OpenApiClient.Groups.Item.QrCodes.QrCodesRequestBuilder.QrCodesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Bitly.OpenApiClient.Groups.Item.QrCodes.QrCodesRequestBuilder.QrCodesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Bulk update can add or remove tags, or archive/un-archive, up to 100 QR codes at a time.Pages QR codes cannot be updated with this endpoint.The response includes a list of QR code ids that were updated.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Bitly.OpenApiClient.Models.QrcBulkUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Bitly.OpenApiClient.Models.QrcBulkUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Groups.Item.QrCodes.QrCodesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Bitly.OpenApiClient.Groups.Item.QrCodes.QrCodesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Bitly.OpenApiClient.Groups.Item.QrCodes.QrCodesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves a list of QR codes matching the filter settings. Values are in reverse chronological order.The pagination occurs by calling the next link in the pagination response object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class QrCodesRequestBuilderGetQueryParameters 
        {
            /// <summary>Whether or not to include archived resources</summary>
            [QueryParameter("archived")]
            public global::Soenneker.Bitly.OpenApiClient.Models.Archived? Archived { get; set; }
            /// <summary>Timestamp as an integer unix epoch (seconds only)</summary>
            [QueryParameter("created_after")]
            public int? CreatedAfter { get; set; }
            /// <summary>Timestamp as an integer unix epoch (seconds only)</summary>
            [QueryParameter("created_before")]
            public int? CreatedBefore { get; set; }
            /// <summary>Filter by the login of the authenticated user that created the QR Code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("creating_login")]
            public string[]? CreatingLogin { get; set; }
#nullable restore
#else
            [QueryParameter("creating_login")]
            public string[] CreatingLogin { get; set; }
#endif
            /// <summary>filter bitlinks by presence of expiration</summary>
            [QueryParameter("has_expiration")]
            public global::Soenneker.Bitly.OpenApiClient.Models.FilterHasExpiration? HasExpiration { get; set; }
            /// <summary>Whether or not QRCode has any render customizations (like color or shape changes)</summary>
            [QueryParameter("has_render_customizations")]
            public global::Soenneker.Bitly.OpenApiClient.Models.FilterHasRenderCustomizations? HasRenderCustomizations { get; set; }
            /// <summary>The hostname and/or path you would like to search (case-insensitive). Subdomains included; query params and fragment ignored.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("hostname_path_query")]
            public string? HostnamePathQuery { get; set; }
#nullable restore
#else
            [QueryParameter("hostname_path_query")]
            public string HostnamePathQuery { get; set; }
#endif
            /// <summary>filter bitlinks by expiration status</summary>
            [QueryParameter("is_expired")]
            public global::Soenneker.Bitly.OpenApiClient.Models.FilterIsExpired? IsExpired { get; set; }
            /// <summary>a filter value if the resource is a GS1 QR code</summary>
            [QueryParameter("is_gs1")]
            public global::Soenneker.Bitly.OpenApiClient.Models.FilterIsGs1? IsGs1 { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("qrc_type")]
            public global::Soenneker.Bitly.OpenApiClient.Models.FilterQrCodeTypeItem[]? QrcType { get; set; }
#nullable restore
#else
            [QueryParameter("qrc_type")]
            public global::Soenneker.Bitly.OpenApiClient.Models.FilterQrCodeTypeItem[] QrcType { get; set; }
#endif
            /// <summary>The value that you would like to search</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("query")]
            public string? Query { get; set; }
#nullable restore
#else
            [QueryParameter("query")]
            public string Query { get; set; }
#endif
            /// <summary>Token used to search next batch of qr codes, only use response from API as input value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("search_after")]
            public string? SearchAfter { get; set; }
#nullable restore
#else
            [QueryParameter("search_after")]
            public string SearchAfter { get; set; }
#endif
            /// <summary>The quantity of items to be be returned</summary>
            [QueryParameter("size")]
            public int? Size { get; set; }
            /// <summary>Filter by given tags</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tags")]
            public string[]? Tags { get; set; }
#nullable restore
#else
            [QueryParameter("tags")]
            public string[] Tags { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
