// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Clicks;
using Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Digital_business_card_downloads;
using Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Overview;
using Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Views;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Bitly.OpenApiClient.Aggregate.Sites
{
    /// <summary>
    /// Builds and executes requests for operations under \aggregate\sites
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SitesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The clicks property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Clicks.ClicksRequestBuilder Clicks
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Clicks.ClicksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The digital_business_card_downloads property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Digital_business_card_downloads.Digital_business_card_downloadsRequestBuilder Digital_business_card_downloads
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Digital_business_card_downloads.Digital_business_card_downloadsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The overview property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Overview.OverviewRequestBuilder Overview
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Overview.OverviewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The views property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Views.ViewsRequestBuilder Views
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Views.ViewsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.SitesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SitesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/aggregate/sites", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.SitesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SitesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/aggregate/sites", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
