// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bitly.OpenApiClient.Groups.Item.Tags
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "bitlink")]
        #pragma warning disable CS1591
        Bitlink,
        #pragma warning restore CS1591
        [EnumMember(Value = "qr_code")]
        #pragma warning disable CS1591
        Qr_code,
        #pragma warning restore CS1591
    }
}
