// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bitly.OpenApiClient.Groups.Item.Codes.Scans.Cities;
using Soenneker.Bitly.OpenApiClient.Groups.Item.Codes.Scans.Countries;
using Soenneker.Bitly.OpenApiClient.Groups.Item.Codes.Scans.Over_time;
using Soenneker.Bitly.OpenApiClient.Groups.Item.Codes.Scans.Top;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Bitly.OpenApiClient.Groups.Item.Codes.Scans
{
    /// <summary>
    /// Builds and executes requests for operations under \groups\{group_guid}\codes\scans
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ScansRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cities property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Groups.Item.Codes.Scans.Cities.CitiesRequestBuilder Cities
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Groups.Item.Codes.Scans.Cities.CitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The countries property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Groups.Item.Codes.Scans.Countries.CountriesRequestBuilder Countries
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Groups.Item.Codes.Scans.Countries.CountriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The over_time property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Groups.Item.Codes.Scans.Over_time.Over_timeRequestBuilder Over_time
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Groups.Item.Codes.Scans.Over_time.Over_timeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The top property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Groups.Item.Codes.Scans.Top.TopRequestBuilder Top
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Groups.Item.Codes.Scans.Top.TopRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Groups.Item.Codes.Scans.ScansRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScansRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/groups/{group_guid}/codes/scans", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Groups.Item.Codes.Scans.ScansRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScansRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/groups/{group_guid}/codes/scans", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
