// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bitly.OpenApiClient.Groups.Item.Links.Clicks.Cities;
using Soenneker.Bitly.OpenApiClient.Groups.Item.Links.Clicks.Countries;
using Soenneker.Bitly.OpenApiClient.Groups.Item.Links.Clicks.Devices;
using Soenneker.Bitly.OpenApiClient.Groups.Item.Links.Clicks.Over_time;
using Soenneker.Bitly.OpenApiClient.Groups.Item.Links.Clicks.Referrers;
using Soenneker.Bitly.OpenApiClient.Groups.Item.Links.Clicks.Top;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Bitly.OpenApiClient.Groups.Item.Links.Clicks
{
    /// <summary>
    /// Builds and executes requests for operations under \groups\{group_guid}\links\clicks
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ClicksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cities property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Groups.Item.Links.Clicks.Cities.CitiesRequestBuilder Cities
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Groups.Item.Links.Clicks.Cities.CitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The countries property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Groups.Item.Links.Clicks.Countries.CountriesRequestBuilder Countries
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Groups.Item.Links.Clicks.Countries.CountriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The devices property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Groups.Item.Links.Clicks.Devices.DevicesRequestBuilder Devices
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Groups.Item.Links.Clicks.Devices.DevicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The over_time property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Groups.Item.Links.Clicks.Over_time.Over_timeRequestBuilder Over_time
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Groups.Item.Links.Clicks.Over_time.Over_timeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The referrers property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Groups.Item.Links.Clicks.Referrers.ReferrersRequestBuilder Referrers
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Groups.Item.Links.Clicks.Referrers.ReferrersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The top property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Groups.Item.Links.Clicks.Top.TopRequestBuilder Top
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Groups.Item.Links.Clicks.Top.TopRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Groups.Item.Links.Clicks.ClicksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClicksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/groups/{group_guid}/links/clicks", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Groups.Item.Links.Clicks.ClicksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClicksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/groups/{group_guid}/links/clicks", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
