// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bitly.OpenApiClient.Models;
using Soenneker.Bitly.OpenApiClient.QrCodes.Item;
using Soenneker.Bitly.OpenApiClient.QrCodes.Static;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Bitly.OpenApiClient.QrCodes
{
    /// <summary>
    /// Builds and executes requests for operations under \qr-codes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QrCodesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The static property</summary>
        public global::Soenneker.Bitly.OpenApiClient.QrCodes.Static.StaticRequestBuilder Static
        {
            get => new global::Soenneker.Bitly.OpenApiClient.QrCodes.Static.StaticRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Bitly.OpenApiClient.qrCodes.item collection</summary>
        /// <param name="position">The QR code ID</param>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.QrCodes.Item.WithQrcode_ItemRequestBuilder"/></returns>
        public global::Soenneker.Bitly.OpenApiClient.QrCodes.Item.WithQrcode_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("qrcode_id", position);
                return new global::Soenneker.Bitly.OpenApiClient.QrCodes.Item.WithQrcode_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.QrCodes.QrCodesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QrCodesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/qr-codes", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.QrCodes.QrCodesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QrCodesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/qr-codes", rawUrl)
        {
        }
        /// <summary>
        /// Create a new QR Code and return its metadata
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.QRCodeMinimal"/></returns>
        /// <param name="body">Customization and content values for a QR code created through the public API</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.BadRequest">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.UpgradeRequired">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.Forbidden">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.NotFound">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.Gone">When receiving a 410 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.MonthlyLimitExceeded">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.InternalError">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeMinimal?> PostAsync(global::Soenneker.Bitly.OpenApiClient.Models.PublicCreateQRCodeRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeMinimal> PostAsync(global::Soenneker.Bitly.OpenApiClient.Models.PublicCreateQRCodeRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Bitly.OpenApiClient.Models.BadRequest.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Bitly.OpenApiClient.Models.UpgradeRequired.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Bitly.OpenApiClient.Models.Forbidden.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Bitly.OpenApiClient.Models.NotFound.CreateFromDiscriminatorValue },
                { "410", global::Soenneker.Bitly.OpenApiClient.Models.Gone.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Bitly.OpenApiClient.Models.MonthlyLimitExceeded.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Bitly.OpenApiClient.Models.InternalError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Bitly.OpenApiClient.Models.QRCodeMinimal>(requestInfo, global::Soenneker.Bitly.OpenApiClient.Models.QRCodeMinimal.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create a new QR Code and return its metadata
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Customization and content values for a QR code created through the public API</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Bitly.OpenApiClient.Models.PublicCreateQRCodeRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Bitly.OpenApiClient.Models.PublicCreateQRCodeRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.QrCodes.QrCodesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Bitly.OpenApiClient.QrCodes.QrCodesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Bitly.OpenApiClient.QrCodes.QrCodesRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
