// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Digital_business_card_downloads.Over_time;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Digital_business_card_downloads
{
    /// <summary>
    /// Builds and executes requests for operations under \aggregate\sites\digital_business_card_downloads
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Digital_business_card_downloadsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The over_time property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Digital_business_card_downloads.Over_time.Over_timeRequestBuilder Over_time
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Digital_business_card_downloads.Over_time.Over_timeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Digital_business_card_downloads.Digital_business_card_downloadsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Digital_business_card_downloadsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/aggregate/sites/digital_business_card_downloads", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Digital_business_card_downloads.Digital_business_card_downloadsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Digital_business_card_downloadsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/aggregate/sites/digital_business_card_downloads", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
