// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bitly.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Bitly.OpenApiClient.QrCodes.Item.Image
{
    /// <summary>
    /// Builds and executes requests for operations under \qr-codes\{qrcode_id}\image
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ImageRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.QrCodes.Item.Image.ImageRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImageRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/qr-codes/{qrcode_id}/image{?format*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.QrCodes.Item.Image.ImageRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImageRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/qr-codes/{qrcode_id}/image{?format*}", rawUrl)
        {
        }
        /// <summary>
        /// Get the image of a given QR Code. The Accept header controls how this is returned (options are &quot;application/json&quot;, &quot;image/svg+xml&quot;, and &quot;image/png&quot;).If the Accept header is &quot;application/json&quot; the format query parameter will determine the image format inside of the json (which will be base64 encoded and prefixed with its mime type as would be suitable for a HTML image src tag).To Return the QR Code image itself, set the Accept header to &quot;image/svg+xml&quot; or &quot;image/png&quot;, or remove the Accept header and set the format query parameter to “svg” or “png” (if no format is specified the default will be “svg”).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.Models.PublicQRCodeImageResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.BadRequest">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.Forbidden">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.NotFound">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.Gone">When receiving a 410 status code</exception>
        /// <exception cref="global::Soenneker.Bitly.OpenApiClient.Models.InternalError">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Bitly.OpenApiClient.Models.PublicQRCodeImageResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Bitly.OpenApiClient.QrCodes.Item.Image.ImageRequestBuilder.ImageRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Bitly.OpenApiClient.Models.PublicQRCodeImageResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Bitly.OpenApiClient.QrCodes.Item.Image.ImageRequestBuilder.ImageRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Bitly.OpenApiClient.Models.BadRequest.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Bitly.OpenApiClient.Models.Forbidden.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Bitly.OpenApiClient.Models.NotFound.CreateFromDiscriminatorValue },
                { "410", global::Soenneker.Bitly.OpenApiClient.Models.Gone.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Bitly.OpenApiClient.Models.InternalError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Bitly.OpenApiClient.Models.PublicQRCodeImageResponse>(requestInfo, global::Soenneker.Bitly.OpenApiClient.Models.PublicQRCodeImageResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get the image of a given QR Code. The Accept header controls how this is returned (options are &quot;application/json&quot;, &quot;image/svg+xml&quot;, and &quot;image/png&quot;).If the Accept header is &quot;application/json&quot; the format query parameter will determine the image format inside of the json (which will be base64 encoded and prefixed with its mime type as would be suitable for a HTML image src tag).To Return the QR Code image itself, set the Accept header to &quot;image/svg+xml&quot; or &quot;image/png&quot;, or remove the Accept header and set the format query parameter to “svg” or “png” (if no format is specified the default will be “svg”).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Bitly.OpenApiClient.QrCodes.Item.Image.ImageRequestBuilder.ImageRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Bitly.OpenApiClient.QrCodes.Item.Image.ImageRequestBuilder.ImageRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bitly.OpenApiClient.QrCodes.Item.Image.ImageRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Bitly.OpenApiClient.QrCodes.Item.Image.ImageRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Bitly.OpenApiClient.QrCodes.Item.Image.ImageRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get the image of a given QR Code. The Accept header controls how this is returned (options are &quot;application/json&quot;, &quot;image/svg+xml&quot;, and &quot;image/png&quot;).If the Accept header is &quot;application/json&quot; the format query parameter will determine the image format inside of the json (which will be base64 encoded and prefixed with its mime type as would be suitable for a HTML image src tag).To Return the QR Code image itself, set the Accept header to &quot;image/svg+xml&quot; or &quot;image/png&quot;, or remove the Accept header and set the format query parameter to “svg” or “png” (if no format is specified the default will be “svg”).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ImageRequestBuilderGetQueryParameters 
        {
            /// <summary>The format type of the image. If there is an image format in the header it takes precedence.</summary>
            [QueryParameter("format")]
            public global::Soenneker.Bitly.OpenApiClient.QrCodes.Item.Image.GetFormatQueryParameterType? Format { get; set; }
        }
    }
}
#pragma warning restore CS0618
