// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Views.Cities;
using Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Views.Countries;
using Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Views.Devices;
using Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Views.Over_time;
using Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Views.Referrers;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Views
{
    /// <summary>
    /// Builds and executes requests for operations under \aggregate\sites\views
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ViewsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cities property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Views.Cities.CitiesRequestBuilder Cities
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Views.Cities.CitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The countries property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Views.Countries.CountriesRequestBuilder Countries
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Views.Countries.CountriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The devices property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Views.Devices.DevicesRequestBuilder Devices
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Views.Devices.DevicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The over_time property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Views.Over_time.Over_timeRequestBuilder Over_time
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Views.Over_time.Over_timeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The referrers property</summary>
        public global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Views.Referrers.ReferrersRequestBuilder Referrers
        {
            get => new global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Views.Referrers.ReferrersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Views.ViewsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ViewsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/aggregate/sites/views", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bitly.OpenApiClient.Aggregate.Sites.Views.ViewsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ViewsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/aggregate/sites/views", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
